"""empty message

Revision ID: 1e024dbda63d
Revises: 90c17522d2e0
Create Date: 2017-02-14 12:22:35.307899

"""

# revision identifiers, used by Alembic.
revision = '1e024dbda63d'
down_revision = '90c17522d2e0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch', 'expires',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.add_column('user', sa.Column('boolean_property_11', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_12', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_13', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_14', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_15', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_16', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_17', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_18', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_19', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('boolean_property_20', sa.Boolean(), nullable=True))
    op.alter_column('user', 'boolean_property_01',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_02',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_03',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_04',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_05',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_06',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_07',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_08',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_09',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_10',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.drop_column('user', 'boolean_property_28')
    op.drop_column('user', 'boolean_property_29')
    op.drop_column('user', 'boolean_property_30')
    op.drop_column('user', 'boolean_property_22')
    op.drop_column('user', 'boolean_property_23')
    op.drop_column('user', 'boolean_property_21')
    op.drop_column('user', 'boolean_property_26')
    op.drop_column('user', 'boolean_property_27')
    op.drop_column('user', 'boolean_property_24')
    op.drop_column('user', 'boolean_property_25')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('boolean_property_25', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_24', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_27', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_26', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_21', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_23', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_22', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_30', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_29', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('boolean_property_28', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('user', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('user', 'boolean_property_10',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_09',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_08',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_07',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_06',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_05',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_04',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_03',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_02',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('user', 'boolean_property_01',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('user', 'boolean_property_20')
    op.drop_column('user', 'boolean_property_19')
    op.drop_column('user', 'boolean_property_18')
    op.drop_column('user', 'boolean_property_17')
    op.drop_column('user', 'boolean_property_16')
    op.drop_column('user', 'boolean_property_15')
    op.drop_column('user', 'boolean_property_14')
    op.drop_column('user', 'boolean_property_13')
    op.drop_column('user', 'boolean_property_12')
    op.drop_column('user', 'boolean_property_11')
    op.alter_column('branch', 'expires',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    ### end Alembic commands ###
