"""empty message

Revision ID: 36548c011f15
Revises: 1f6dd9751334
Create Date: 2016-11-28 23:22:55.347538

"""

# revision identifiers, used by Alembic.
revision = '36548c011f15'
down_revision = '1f6dd9751334'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch', 'expires',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.alter_column('comment', 'content',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.Unicode(length=2000),
               existing_nullable=False)
    op.alter_column('user', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text(u"'0'"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text(u"'0'"))
    op.alter_column('comment', 'content',
               existing_type=sa.Unicode(length=2000),
               type_=mysql.VARCHAR(length=400),
               existing_nullable=False)
    op.alter_column('branch', 'expires',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    ### end Alembic commands ###
