"""Add file regexp to named tags

Revision ID: 50e6c12a9a06
Revises: 280d0531befe
Create Date: 2017-08-21 12:51:39.569711

"""

# revision identifiers, used by Alembic.
revision = '50e6c12a9a06'
down_revision = '280d0531befe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('named_tag', sa.Column('file_regexp', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('named_tag', 'file_regexp')
    # ### end Alembic commands ###
