"""empty message

Revision ID: 7d18e1840349
Revises: fea7f317c6a9
Create Date: 2016-10-30 17:04:40.977720

"""

# revision identifiers, used by Alembic.
revision = '7d18e1840349'
down_revision = 'fea7f317c6a9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branch_tag')
    op.add_column('thread', sa.Column('flag', sa.String(length=10), nullable=False))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'flag')
    op.create_table('branch_tag',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('thread_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('branch_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], [u'branch.id'], name=u'branch_tag_ibfk_2'),
    sa.ForeignKeyConstraint(['thread_id'], [u'thread.id'], name=u'branch_tag_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
