"""Add user-thread relation to store read

Revision ID: d838fb3c676d
Revises: 9b31d50ade9f
Create Date: 2017-08-17 14:10:28.755307

"""

# revision identifiers, used by Alembic.
revision = 'd838fb3c676d'
down_revision = '9b31d50ade9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_read_thread',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_read_thread')
    # ### end Alembic commands ###
