"""Reduce size of email

Revision ID: f4a5152337aa
Revises: 50e6c12a9a06
Create Date: 2017-09-15 14:40:29.386540

"""

# revision identifiers, used by Alembic.
revision = 'f4a5152337aa'
down_revision = '50e6c12a9a06'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=75),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.String(length=75),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
